#!/usr/bin/env python3
"""
MathHead — API reference generator (ROADMAP Phase 8 [S]).

Single source of truth: tools REGISTERED with the MCP server. This script reads
their name, signature (parameters + defaults) and description and generates
`docs/api-reference.md`. `tests/test_api_reference.py` enforces that the generated
output matches the committed file (no drift).

Usage:
    python scripts/gen_api_reference.py            # write the file
    python scripts/gen_api_reference.py --check     # is it up to date (0/1)
"""
from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

from mathhead.server.mcp_server import mcp

_OUT = Path(__file__).parent.parent / "docs" / "api-reference.md"


def _signature(name: str, schema: dict) -> str:
    props = (schema or {}).get("properties", {}) or {}
    required = set((schema or {}).get("required", []) or [])
    parts = []
    for pname, spec in props.items():
        if pname in required:
            parts.append(pname)
        else:
            default = spec.get("default", None)
            parts.append(f"{pname}={default!r}" if default is not None else f"{pname}=None")
    return f"{name}({', '.join(parts)})"


def generate() -> str:
    tools = asyncio.run(mcp.list_tools())
    lines = [
        "# MathHead — API Reference (auto-generated)",
        "",
        "> **WARNING:** This file is generated by `scripts/gen_api_reference.py` from",
        "> the tools registered with MCP. DO NOT EDIT BY HAND. To update:",
        "> `python scripts/gen_api_reference.py`. Contract details: `docs/mcp-api.md`.",
        "",
        f"Total **{len(tools)} tools**.",
        "",
    ]
    for t in tools:
        desc = (t.description or "").strip().splitlines()
        first = desc[0].strip() if desc else ""
        lines.append(f"### `{_signature(t.name, t.inputSchema)}`")
        lines.append("")
        lines.append(first)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="MathHead API reference generator")
    ap.add_argument("--check", action="store_true", help="only check if up to date")
    args = ap.parse_args()
    content = generate()
    if args.check:
        current = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
        if current != content:
            print("api-reference.md OUT OF DATE — run `python scripts/gen_api_reference.py`")
            return 1
        print("api-reference.md up to date.")
        return 0
    _OUT.write_text(content, encoding="utf-8")
    print(f"written: {_OUT}  ({content.count('### ')} tools)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
