name = "mathhead_lean"
version = "1.0.0"
defaultTargets = ["MathHead"]

[[require]]
name = "mathlib"
path = ".lake/packages/mathlib"

[[require]]
name = "plausible"
path = ".lake/packages/plausible"

[[require]]
name = "LeanSearchClient"
path = ".lake/packages/LeanSearchClient"

[[require]]
name = "importGraph"
path = ".lake/packages/importGraph"

[[require]]
name = "proofwidgets"
path = ".lake/packages/proofwidgets"

[[require]]
name = "aesop"
path = ".lake/packages/aesop"

[[require]]
name = "Qq"
path = ".lake/packages/Qq"

[[require]]
name = "batteries"
path = ".lake/packages/batteries"

[[require]]
name = "Cli"
path = ".lake/packages/Cli"

[[lean_lib]]
name = "MathHead"
